version:                "3"
services:
    webapp:
        build:
            context:    .
            dockerfile: Dockerfile-webapp
        command:        carmel exec -- perl hello-world.pl
        ports:
            - "3000:9876"
